#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -x

juju-log "install script"

export TERM=linux

#RELEASE_CODE=`lsb_release -a | awk '/Codename/ { print $2 }'`

# Add the Hadoop PPA
juju-log "Adding ppa"
apt-add-repository ppa:mark-mims/hadoop
#apt-add-repository ppa:canonical-sig/thirdparty
juju-log "updating cache"
apt-get update

# only necessary on oneiric but shouldn't break anything elsewhere
HOSTNAME=`hostname -f`
IP_ADDRESS=`hostname -f | xargs dig +short`
#sed -i "s/\(.*${HOSTNAME}.*\)/#\1/" /etc/hosts
sed -i "s/127.0.1.1\(.*${HOSTNAME}.*\)/${IP_ADDRESS}\1/" /etc/hosts

# Install the packages
juju-log "installing packages"
DEBIAN_FRONTEND=noninteractive apt-get install -y hadoop-0.20-datanode hadoop-0.20-tasktracker

# Open the necessary ports
if [ -x /usr/bin/open-port ];then
   open-port 50010/TCP
   open-port 50020/TCP
   open-port 50030/TCP
   open-port 50105/TCP
   open-port 54310/TCP
   open-port 54311/TCP
   open-port 50060/TCP
   open-port 50070/TCP
   open-port 50075/TCP
   open-port 50090/TCP
fi
