#!/bin/bash

set -x

juju-log "install script"

#RELEASE_CODE=`lsb_release -cs`

juju-log "Adding ppa"
apt-add-repository "deb http://package.mapr.com/releases/v1.1.1/ubuntu/ mapr optional"
apt-get update

HOSTNAME=`hostname -f`
IP_ADDRESS=`hostname -f | xargs dig +short`
juju-log "Private IP: ${IP_ADDRESS}"

# fixing hosts entry added by cloudinit
sed -i "s/127.0.1.1\(.*${HOSTNAME}.*\)/${IP_ADDRESS}\1/" /etc/hosts

juju-log "installing packages"

DEBIAN_FRONTEND=noninteractive apt-get install -y hadoop-0.20-datanode
DEBIAN_FRONTEND=noninteractive apt-get install -y hadoop-0.20-tasktracker

if [ -x /usr/bin/open-port ];then
   open-port 50010/TCP
   open-port 50020/TCP
   open-port 50030/TCP
   open-port 50105/TCP
   open-port 54310/TCP
   open-port 54311/TCP
   open-port 50060/TCP
   open-port 50070/TCP
   open-port 50075/TCP
   open-port 50090/TCP
fi
